version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      # --- SECCIÓN CORREGIDA ---
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://myuser:mypass@db:3306/mydb
      - PYTHONPATH=/app
    volumes:
      - ./app:/app
    command: ["./wait-for-mysql.sh", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


volumes:
  mysql_data: