version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck: # Añade esta sección
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}"]
      interval: 10s # Comprueba cada 10 segundos
      timeout: 5s   # Espera 5 segundos por una respuesta
      retries: 10   # Intenta 10 veces antes de marcar como no saludable
      start_period: 30s # Espera 30 segundos después de iniciar el contenedor antes de la primera comprobación

  app:
    build: ./app
    depends_on:
      db: # Modifica esta sección
        condition: service_healthy # Espera a que el healthcheck de 'db' pase
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://myuser:mypass@db:3306/mydb
      - PYTHONPATH=/app
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data: