import tkinter as tk
ventana = tk.Tk()
ventana.geometry("640x480")
etiqueta = tk.Label(ventana, text="alamaula")
etiqueta.pack()
marco1 = tk.Frame()
marco1.configure(width="1280", height="240", bg="blue")
marco2 = tk.Frame()
marco2.configure(width="1280", height="240", bg="yellow")
marco3 = tk.Frame()
marco3.configure(width="1280", height="240", bg="blue")
marco1.pack()
marco2.pack()
marco3.pack()
ventana.mainloop()