# fly.toml app configuration file generated for proyecto-integrador on 2025-08-18T00:14:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proyecto-integrador'
primary_region = 'eze'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
